import { switchMap, delay, flatMap } from 'rxjs/operators';
import { Component, OnInit, OnDestroy, Input, Output, EventEmitter, ChangeDetectorRef, ViewChild } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { SubscriptionLike, Subject, of } from 'rxjs';
import { MatDialog } from '@angular/material/dialog';

import { WordAskedReasons } from '../../../../layout/seed-word-dialog/seed-word-dialog.component';
import { MsgBarService } from '../../../../../services/msg-bar.service';
import { ConfirmationParams, ConfirmationComponent, DefaultConfirmationButtons } from '../../../../layout/confirmation/confirmation.component';
import { OperationError } from '../../../../../utils/operation-error';
import { processServiceError } from '../../../../../utils/errors';
import { WalletTypes } from '../../../../../services/wallet-operations/wallet-objects';
import { AppConfig } from '../../../../../app.config';
import { WalletUtilsService } from '../../../../../services/wallet-operations/wallet-utils.service';
import { CoinService } from '../../../../../services/coin.service';
import { AssistedSeedFieldComponent } from './assisted-seed-field/assisted-seed-field.component';

/**
 * Data entered in an instance of CreateWalletFormComponent.
 */
export class WalletFormData {
  /**
   * If the form is for creating a new wallet (true) or loading a walled using a seed (false).
   */
  creatingNewWallet: boolean;
  /**
   * Label for the wallet.
   */
  label: string;
  /**
   * Wallet type.
   */
  type: WalletTypes;
  /**
   * xPub key entered by the user.
   */
  xPub: string;
  /**
   * Passphrase for the wallet.
   */
  passphrase: string;
  /**
   * If set, the wallet must be encrypted with this password.
   */
  password: string;
  /**
   * If true, the seed was entered using the assisted mode.
   */
  enterSeedWithAssistance: boolean;
  /**
   * Last automatically generated seed.
   */
  lastAutogeneratedSeed: string;
  /**
   * Last seed the user entered using the manual mode.
   */
  lastCustomSeed: string;
  /**
   * Last seed the user entered using the assisted mode.
   */
  lastAssistedSeed: string;
  /**
   * If creating a new wallet, how many words the automatically generated seed for the
   * assisted mode has. If loading a wallet, how many words the seed entered by the user has.
   */
  numberOfWords: number;
  /**
   * If the user entered a standard seed, if the manual mode was being used.
   */
  customSeedIsNormal: boolean;
  /**
   * If the advanced options panel was open.
   */
  advancedOptionsShown: boolean;
}

/**
 * Form for creating or loading a software wallet.
 */
@Component({
  selector: 'app-create-wallet-form',
  templateUrl: './create-wallet-form.component.html',
  styleUrls: ['./create-wallet-form.component.scss'],
})
export class CreateWalletFormComponent implements OnInit, OnDestroy {
  // Component for entering the seed using the assisted mode.
  @ViewChild('assistedSeed') assistedSeed: AssistedSeedFieldComponent;

  // If the form is for creating a new wallet (true) or loading a walled using a seed (false).
  @Input() create: boolean;
  // If the form is being shown on the wizard (true) or not (false).
  @Input() onboarding: boolean;
  // Allows to deactivate the form while the system is busy.
  @Input() busy = false;
  // Emits when the user asks for the wallet ot be created.
  @Output() createRequested = new EventEmitter<void>();

  form: FormGroup;
  // If true, there are many coins to select from.
  hasManyCoins: boolean;
  // If true, the user must enter the ssed using the asisted mode.
  enterSeedWithAssistance = true;
  // If the user entered a standard seed using the manual mode.
  customSeedIsNormal = true;
  // If the user entered a non-standard seed using the manual mode and confirmed to use it.
  customSeedAccepted = false;
  // If the user selected that the wallet must be created encrypted.
  encrypt = true;
  // Last automatically generated seed.
  lastAutogeneratedSeed = '';
  // How many words the last autogenerated seed for the assisted mode has, when creating
  // a new wallet.
  numberOfAutogeneratedWords = 0;
  // If the system is currently checking the custom seed entered by the user.
  checkingCustomSeed = false;
  // If the advanced options must be shown on the UI.
  showAdvancedOptions = false;
  // If the passphrase warning must be shown.
  showPassphraseWarning = false;
  // If the user entered a passphrase and confirmed the desire to use it.
  passphraseWarningAccepted = false;

  // Vars with the wallet types the currently selected coin is compatible with.
  hardwareWalletsAllowedForCoin = true;
  softwareWalletsAllowedForCoin = true;
  legacyAllowedForCoin = true;
  bip44AllowedForCoin = true;
  xPubAllowedForCoin = true;
  // If the wallet type options must be shown in the form.
  showWalletTypeOptions = true;

  bip44Enabled = AppConfig.bip44Enabled;
  xPubEnabled = AppConfig.xPubEnabled;

  walletTypes = WalletTypes;
  wordAskedReasons = WordAskedReasons;

  // Emits every time the seed should be checked again, to know if it is a standard seed.
  private seed: Subject<string> = new Subject<string>();

  private defaultWalletType: WalletTypes = this.create && this.bip44Enabled ? WalletTypes.Bip44 : WalletTypes.Deterministic;

  private coinSubscription: SubscriptionLike;
  private seedValiditySubscription: SubscriptionLike;
  private formSubscriptions: SubscriptionLike[] = [];

  // Saves the words the user enters while using the assisted mode.
  private partialSeed: string[];

  constructor(
    private walletUtilsService: WalletUtilsService,
    private dialog: MatDialog,
    private msgBarService: MsgBarService,
    private changeDetector: ChangeDetectorRef,
    coinService: CoinService,
  ) {
    this.hasManyCoins = coinService.coins.length > 1;

    // Check the wallet types the currently selected coin is compatible with.
    this.coinSubscription = coinService.currentCoin.subscribe(currentCoin => {
      this.hardwareWalletsAllowedForCoin = !!currentCoin.skywalletCoinType;
      this.softwareWalletsAllowedForCoin = currentCoin.coinTypeFeatures.softwareWallets;

      let availableTypes = 0;
      this.legacyAllowedForCoin = currentCoin.coinTypeFeatures.legacySoftwareWallets;
      availableTypes += currentCoin.coinTypeFeatures.legacySoftwareWallets ? 1 : 0;
      this.bip44AllowedForCoin = currentCoin.coinTypeFeatures.bip44SoftwareWallets;
      availableTypes += currentCoin.coinTypeFeatures.bip44SoftwareWallets && this.bip44Enabled ? 1 : 0;
      this.xPubAllowedForCoin = currentCoin.coinTypeFeatures.xPubSoftwareWallets;
      availableTypes += currentCoin.coinTypeFeatures.xPubSoftwareWallets && this.xPubEnabled ? 1 : 0;

      this.showWalletTypeOptions = availableTypes > 1;

      this.updateSoftwareWalletTypes(false, this.create);
    });
  }

  ngOnInit() {
    if (!this.onboarding) {
      this.initForm();
    } else {
      this.initForm(false, null);
    }
  }

  ngOnDestroy() {
    this.msgBarService.hide();
    this.coinSubscription.unsubscribe();
    this.seedValiditySubscription.unsubscribe();
    this.removeFormSubscriptions();
    this.createRequested.complete();
  }

  // Allows to know if the form is valid.
  get isValid(): boolean {
    // Check if the basic part of the form is valid.
    if (this.form.valid && (!this.activatePassphraseField || !this.showPassphraseWarning || this.passphraseWarningAccepted)) {
      // If the user selected a wallet type which needs a seed.
      if (!this.activateXPubField) {
        // When entering the seed manually, the system must have finished checking the seed and the
        // seed must be normal or the user must confirm the usage of a custom seed. When using the
        // assisted mode, the user must enter the seed in the appropriate way.
        if (!this.checkingCustomSeed) {
          if ((!this.enterSeedWithAssistance && (this.customSeedIsNormal || this.customSeedAccepted)) ||
          (this.enterSeedWithAssistance && this.assistedSeed.lastAssistedSeed)) {
            return true;
          }
        }
      } else {
        // If no seed is needed, check is the user entered the xPub key.
        if (this.form.get('xpub').value) {
          return true;
        }
      }
    }

    // If none of the previous alternatives was meet, the form is not valid.
    return false;
  }

  // Allows to know if the passphrase field must be active.
  get activatePassphraseField(): boolean {
    // Show it only if the user selected the bip44 type.
    if (this.form && this.form.get('type').value === WalletTypes.Bip44) {
      return true;
    }

    return false;
  }

  // Allows to know if the xPub field must be active.
  get activateXPubField(): boolean {
    // Show it only if the user selected the xPub type.
    if (this.form && this.form.get('type').value === WalletTypes.XPub) {
      return true;
    }

    return false;
  }

  // Sets if the user has acepted to use a manually entered non-standard seed.
  onCustomSeedAcceptance(event) {
    this.customSeedAccepted = event.checked;
  }

  // Sets if the user has acepted to use a passphrase.
  onPassphraseWarningAcceptance(event) {
    this.passphraseWarningAccepted = event.checked;
  }

  // Sets the user selection regarding whether the wallet must be encrypted or not.
  setEncrypt(event) {
    this.encrypt = event.checked;
    this.form.updateValueAndValidity();
  }

  // Returns the data entered on the form.
  getData(): WalletFormData {
    return {
      creatingNewWallet: this.create,
      type: this.form.value.type,
      label: this.form.value.label,
      lastAssistedSeed: this.assistedSeed.lastAssistedSeed,
      xPub: this.form.value.xpub ? (this.form.value.xpub as string).trim() : this.form.value.xpub,
      passphrase: this.form.value.passphrase,
      password: !this.onboarding && this.encrypt ? this.form.value.password : null,
      enterSeedWithAssistance: this.enterSeedWithAssistance,
      lastAutogeneratedSeed: this.lastAutogeneratedSeed,
      lastCustomSeed: this.form.value.seed,
      numberOfWords: !this.create ? this.form.value.number_of_words : this.numberOfAutogeneratedWords,
      customSeedIsNormal: this.customSeedIsNormal,
      advancedOptionsShown: this.showAdvancedOptions,
    };
  }

  // Switches between the assisted mode and the manual mode for entering the seed.
  changeSeedType() {
    this.msgBarService.hide();

    if (!this.enterSeedWithAssistance) {
      this.enterSeedWithAssistance = true;
      this.removeConfirmations();
    } else {
      // Ask for confirmation before making the change.
      const confirmationParams: ConfirmationParams = {
        text: this.create ? 'wallet.new.seed.custom-seed-warning-text' : 'wallet.new.seed.custom-seed-warning-text-recovering',
        headerText: 'common.warning-title',
        checkboxText: this.create ? 'common.generic-confirmation-check' : null,
        defaultButtons: DefaultConfirmationButtons.ContinueCancel,
        redTitle: true,
      };

      ConfirmationComponent.openDialog(this.dialog, confirmationParams).afterClosed().subscribe(confirmationResult => {
        if (confirmationResult) {
          this.enterSeedWithAssistance = false;
          this.removeConfirmations();
        }
      });
    }
  }

  /**
   * Updates the value of defaultWalletType, taking into account the wallet types
   * compatible with the currently selected coin. After that, the fields in the advanced
   * options panel are resetted.
   * @param updateDefaultOnly If true, the fields in the advanced options panel
   * are not resetted.
   * @param creatingWallet If the form is being show for creating a new wallet (true) or
   * loading a walled using a seed (false).
   */
  private updateSoftwareWalletTypes(updateDefaultOnly: boolean, creatingWallet: boolean) {
    if (this.form) {
      // find a valid default.
      if (this.legacyAllowedForCoin && this.bip44AllowedForCoin) {
        this.defaultWalletType = creatingWallet && this.bip44Enabled ? WalletTypes.Bip44 : WalletTypes.Deterministic;
      } else {
        if (this.bip44AllowedForCoin && this.bip44Enabled) {
          this.defaultWalletType = WalletTypes.Bip44;
        } else {
          this.defaultWalletType = WalletTypes.Deterministic;
        }
      }

      // Update the form.
      if (!updateDefaultOnly) {
        this.showAdvancedOptions = true;
        this.finishTogglingAdvancedOptions();
      }
    }
  }

  /**
   * Inits or resets the form.
   * @param create If the form is for creating a new wallet (true) or loading a walled using
   * a seed (false). Use null to avoid changing the value set using the html tag.
   * @param data Data to populate the form.
   */
  initForm(create: boolean = null, data: WalletFormData = null) {
    this.msgBarService.hide();

    create = create !== null ? create : this.create;

    this.lastAutogeneratedSeed = '';
    this.enterSeedWithAssistance = true;

    const validators = [];
    if (create) {
      validators.push(this.seedMatchValidator.bind(this));
    }
    if (!this.onboarding) {
      // The password is entered on a different form while using the wizard.
      validators.push(this.validatePasswords.bind(this));
    }
    validators.push(this.mustHaveSeed.bind(this));
    validators.push(this.canCreateSoftwareWallets.bind(this));

    this.form = new FormGroup({}, validators);
    this.form.addControl('label', new FormControl(data ? data.label : '', [Validators.required]));
    this.form.addControl('seed', new FormControl(data ? data.lastCustomSeed : ''));
    this.form.addControl('confirm_seed', new FormControl(data ? data.lastCustomSeed : ''));
    this.form.addControl('xpub', new FormControl(data ? data.xPub : ''));
    this.form.addControl('type', new FormControl(data ? data.type : '', [Validators.required]));
    this.form.addControl('passphrase', new FormControl(data ? data.passphrase : ''));
    this.form.addControl('password', new FormControl());
    this.form.addControl('confirm_password', new FormControl());
    this.form.addControl('number_of_words', new FormControl(!this.create && data && data.numberOfWords ? data.numberOfWords : 12));

    this.removeConfirmations(false);

    // Create a new random seed.
    if (create && !data) {
      this.generateSeed(128);
    }

    this.showAdvancedOptions = false;
    this.showPassphraseWarning = false;

    // Use the provided data.
    if (data) {
      this.enterSeedWithAssistance = data.enterSeedWithAssistance;
      this.assistedSeed.lastAssistedSeed = data.lastAssistedSeed;
      this.lastAutogeneratedSeed = data.lastAutogeneratedSeed;
      this.customSeedAccepted = true;
      this.customSeedIsNormal = data.customSeedIsNormal;

      this.showAdvancedOptions = data.advancedOptionsShown;
      this.showPassphraseWarning = create && !!data.passphrase;
      this.passphraseWarningAccepted = true;

      if (this.create) {
        this.numberOfAutogeneratedWords = data.numberOfWords;
      }
    }

    this.updateSoftwareWalletTypes(!!data, create);

    this.removeFormSubscriptions();

    this.formSubscriptions = [];

    // Ensure the UI is updated quickly.
    this.formSubscriptions.push(
      this.form.get('type').statusChanges.subscribe(() => {
        setTimeout(() => {
          this.changeDetector.detectChanges();
        });
      }),
    );

    // Check the custom seed and invaidate the custom seed confirmation.
    this.formSubscriptions.push(
      this.form.get('seed').statusChanges.subscribe(() => {
        this.customSeedAccepted = false;
        this.seed.next(this.form.get('seed').value);
      }),
    );
    this.formSubscriptions.push(
      this.form.get('confirm_seed').statusChanges.subscribe(() => {
        this.customSeedAccepted = false;
        this.seed.next(this.form.get('seed').value);
      }),
    );

    // Cancel the passphrase confirmation and show the warning if needed.
    this.formSubscriptions.push(
      this.form.get('passphrase').statusChanges.subscribe(() => {
        this.passphraseWarningAccepted = false;
        this.showPassphraseWarning = this.create && !!this.form.get('passphrase').value;
      }),
    );
    this.subscribeToSeedValidation();
  }

  // Generates a new random seed for when creating a new wallet.
  generateSeed(entropy: number) {
    if (entropy === 128) {
      this.numberOfAutogeneratedWords = 12;
    } else {
      this.numberOfAutogeneratedWords = 24;
    }

    this.walletUtilsService.generateSeed(entropy).subscribe(seed => {
      this.lastAutogeneratedSeed = seed;
      this.form.get('seed').setValue(seed);
      this.removeConfirmations();
    });
  }

  // Request the wallet to be created or loaded.
  requestCreation() {
    this.createRequested.emit();
  }

  // Shows or hides the advanced options.
  toggleAdvancedOptions() {
    // Ask for confirmation if the user made changes and the panel will be closed.
    if (this.showAdvancedOptions && (this.form.get('passphrase').value || this.form.get('type').value !== this.defaultWalletType)) {
      const confirmationParams: ConfirmationParams = {
        text: 'wallet.new.advanced-options-close-warning',
        defaultButtons: DefaultConfirmationButtons.YesNo,
      };

      ConfirmationComponent.openDialog(this.dialog, confirmationParams).afterClosed().subscribe(confirmationResult => {
        if (confirmationResult) {
          this.finishTogglingAdvancedOptions();
        }
      });
    } else {
      this.finishTogglingAdvancedOptions();
    }
  }

  private finishTogglingAdvancedOptions() {
    this.showAdvancedOptions = !this.showAdvancedOptions;
    // Reset the values.
    this.form.get('passphrase').setValue('');
    this.form.get('type').setValue(this.defaultWalletType);
  }

  /**
   * Removes the confirmations the user could have made for accepting the seed.
   * @param cleanSecondSeedField If true, the second field for manually entering a seed (the
   * one used for confirming the seed by entering it again) will be cleaned.
   */
  private removeConfirmations(cleanSecondSeedField = true) {
    this.customSeedAccepted = false;
    if (this.assistedSeed) {
      this.assistedSeed.lastAssistedSeed = null;
    }
    this.passphraseWarningAccepted = false;
    if (cleanSecondSeedField) {
      this.form.get('confirm_seed').setValue('');
    }
    this.form.updateValueAndValidity();
  }

  // Makes the component continually check if the user has manually entered a non-standard seed.
  private subscribeToSeedValidation() {
    if (this.seedValiditySubscription) {
      this.seedValiditySubscription.unsubscribe();
    }

    this.seedValiditySubscription = this.seed.asObservable().pipe(switchMap(seed => {
      // Verify the seed if it was entered manually and was confirmed.
      if ((!this.seedMatchValidator() || !this.create) && !this.enterSeedWithAssistance && seed.length > 0) {
        this.checkingCustomSeed = true;

        return of(0).pipe(delay(500), flatMap(() => this.walletUtilsService.verifySeed(seed)));
      } else {
        return of(true);
      }
    })).subscribe(valid => {
      this.checkingCustomSeed = false;
      this.customSeedIsNormal = valid;
    }, (error: OperationError) => {
      this.checkingCustomSeed = false;
      // If the node said the seed is not standard, ask the user for confirmation before
      // allowing to use it.
      error = processServiceError(error);
      if (error && error.originalError && error.originalError.status === 422) {
        this.customSeedIsNormal = false;
      } else {
        this.customSeedIsNormal = true;
        this.msgBarService.showWarning('wallet.new.seed-checking-error');
      }
      this.subscribeToSeedValidation();
    });
  }

  // Validator that, if the wallet must be encrypted, checks if the 2 password match.
  private validatePasswords() {
    if (this.encrypt) {
      if (this.form && this.form.get('password') && this.form.get('confirm_password')) {
        if (this.form.get('password').value) {
          if (this.form.get('password').value !== this.form.get('confirm_password').value) {
            return { NotEqual: true };
          }
        } else {
          return { Required: true };
        }
      } else {
        return { Required: true };
      }
    }

    return null;
  }

  // Validator that checks if the currently selected coin is compatible with software wallets.
  private canCreateSoftwareWallets() {
    if (!this.softwareWalletsAllowedForCoin) {
      return { invalid: true };
    }

    return null;
  }

  // Validator that checks if a seed has been manually entered, if the assisted mode is
  // not activated and the selected wallet type is not xPub.
  private mustHaveSeed() {
    if (!this.enterSeedWithAssistance && !this.activateXPubField) {
      if ((this.form.get('seed').value as string) === '') {
        return { Required: true };
      }
    }

    return null;
  }

  // Validator that checks if the manually entered seeds match, if the assisted mode is
  // not activated and the selected wallet type is not xPub.
  private seedMatchValidator() {
    if (this.enterSeedWithAssistance || this.activateXPubField) {
      return null;
    }

    if (this.form && this.form.get('seed') && this.form.get('confirm_seed')) {
      return this.form.get('seed').value === this.form.get('confirm_seed').value ? null : { NotEqual: true };
    } else {
      return { NotEqual: true };
    }
  }

  private removeFormSubscriptions() {
    this.formSubscriptions.forEach(s => s.unsubscribe());
  }
}
