language: go
go:
  # - "1.11.x" At minimum the code should run make check on the latest two go versions in the default linux environment provided by Travis.
  - "1.13.x"

dist: xenial

matrix:
  include:
    - os: linux
    - os: osx
      # Do not start osx build for PR
      if: type != pull_request
      osx_image: xcode8

before_install:
  - nvm install 10.16

install:
  - go get -u github.com/FiloSottile/vendorcheck
  - make install-linters
  - make install-deps-ui

script:
  - make lint-ui
  - make build-ui
